// ====================================================================
// 服务条款页面（公开，无需登录）
// ====================================================================
// 内容按 locale 双语内联：英文为主，中文翻译
// 法律文本不放进 messages/*.json，保持简单
// ====================================================================

import type { Metadata } from "next";
import { setRequestLocale, getLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";

// 动态 SEO 元数据（根据语言切换）
export async function generateMetadata(): Promise<Metadata> {
  const locale = await getLocale();

  const titles = {
    en: "Terms of Service | WriteFit",
    zh: "服务条款 | WriteFit",
  };

  const descriptions = {
    en: "The terms that govern your use of WriteFit, the AI writing coach for daily writing practice.",
    zh: "规范你使用 WriteFit（AI 写作教练）的条款。",
  };

  return {
    title: titles[locale as "en" | "zh"],
    description: descriptions[locale as "en" | "zh"],
    alternates: {
      canonical: "https://writefit.app/terms",
      languages: {
        en: "https://writefit.app/terms",
        zh: "https://writefit.app/zh/terms",
      },
    },
  };
}

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return locale === "zh" ? <TermsZh /> : <TermsEn />;
}

// 共享的排版类名（项目没有 @tailwindcss/typography，手写 prose 风格）
const h2Class = "mt-10 mb-4 text-2xl font-semibold tracking-tight";
const pClass = "mb-4 text-muted-foreground leading-7";
const ulClass = "mb-4 list-disc pl-6 space-y-2 text-muted-foreground leading-7";

function TermsEn() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="mb-2 text-4xl font-bold tracking-tight">
        Terms of Service
      </h1>
      <p className="mb-10 text-sm text-muted-foreground">
        Last updated: July 18, 2026
      </p>

      <p className={pClass}>
        These Terms of Service (&quot;Terms&quot;) govern your use of WriteFit.
        By creating an account or using the service, you agree to these Terms.
      </p>

      <h2 className={h2Class}>1. The Service</h2>
      <p className={pClass}>
        WriteFit is an AI writing training tool. It gives you daily writing
        exercises, stores your practice history, and generates feedback on
        your writing through a third-party AI provider that you configure.
      </p>

      <h2 className={h2Class}>2. Your Account</h2>
      <ul className={ulClass}>
        <li>
          You are responsible for keeping your account credentials
          confidential and for all activity under your account.
        </li>
        <li>
          You must provide accurate registration information and keep it up to
          date.
        </li>
        <li>
          You must be at least 13 years old (or the minimum age required in
          your jurisdiction) to use WriteFit.
        </li>
      </ul>

      <h2 className={h2Class}>3. Your Content</h2>
      <p className={pClass}>
        You retain full ownership of everything you write in WriteFit —
        exercises, drafts, sentences, and ideas. We claim no intellectual
        property rights over your content. We store and process it solely to
        provide the service to you.
      </p>

      <h2 className={h2Class}>4. AI Feedback</h2>
      <p className={pClass}>
        Feedback generated by AI is provided for reference and practice
        purposes only. It may be inaccurate, incomplete, or unsuitable for
        your situation, and it does not constitute professional advice of any
        kind (including legal, medical, educational, or career advice). You
        are responsible for how you use it.
      </p>

      <h2 className={h2Class}>5. Bring Your Own Key (BYOK)</h2>
      <p className={pClass}>
        WriteFit lets you connect your own third-party AI provider account
        with your own API key. When you do:
      </p>
      <ul className={ulClass}>
        <li>
          Your relationship with the AI provider — including pricing, usage
          limits, and data handling — is solely between you and that provider.
        </li>
        <li>
          You are responsible for complying with the provider&apos;s terms and
          for any charges incurred on your API key.
        </li>
        <li>
          Your API key is stored in your browser&apos;s localStorage, not on
          our servers. Keeping it safe is your responsibility.
        </li>
      </ul>

      <h2 className={h2Class}>6. Acceptable Use</h2>
      <p className={pClass}>You agree not to:</p>
      <ul className={ulClass}>
        <li>Abuse the service, interfere with it, or disrupt other users.</li>
        <li>
          Reverse engineer, decompile, or attempt to extract the source code
          of the service, except where permitted by law.
        </li>
        <li>
          Scrape, crawl, or send automated bulk requests to the service or its
          APIs.
        </li>
        <li>
          Use the service for anything unlawful, harmful, or infringing on
          others&apos; rights.
        </li>
      </ul>

      <h2 className={h2Class}>7. Availability</h2>
      <p className={pClass}>
        WriteFit is provided &quot;as is&quot; and &quot;as available&quot;.
        We do not guarantee that the service will be uninterrupted, timely,
        secure, or error-free, and we may modify, suspend, or discontinue any
        part of it at any time.
      </p>

      <h2 className={h2Class}>8. Termination</h2>
      <p className={pClass}>
        You can stop using WriteFit and delete your account at any time from
        the Settings page. We may suspend or terminate accounts that violate
        these Terms.
      </p>

      <h2 className={h2Class}>9. Limitation of Liability</h2>
      <p className={pClass}>
        To the maximum extent permitted by law, WriteFit and its operators
        will not be liable for any indirect, incidental, special,
        consequential, or punitive damages, or for any loss of data, profits,
        or goodwill, arising from your use of the service. Our total liability
        for any claim related to the service is limited to the amount you paid
        us in the twelve months before the claim (or zero if the service was
        free for you).
      </p>

      <h2 className={h2Class}>10. Changes to These Terms</h2>
      <p className={pClass}>
        We may update these Terms from time to time. When we do, we will
        revise the &quot;Last updated&quot; date above. Continued use of
        WriteFit after a change means you accept the updated Terms.
      </p>

      <h2 className={h2Class}>11. Contact</h2>
      <p className={pClass}>
        If you have any questions about these Terms, contact us at{" "}
        <a
          href="mailto:aifeefee70@gmail.com"
          className="text-primary hover:underline"
        >
          aifeefee70@gmail.com
        </a>
        .
      </p>

      <p className="mt-12 border-t border-border pt-6 text-sm">
        <Link href="/" className="text-primary hover:underline">
          &larr; Back to home
        </Link>
      </p>
    </main>
  );
}

function TermsZh() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="mb-2 text-4xl font-bold tracking-tight">服务条款</h1>
      <p className="mb-10 text-sm text-muted-foreground">
        最后更新：2026 年 7 月 18 日
      </p>

      <p className={pClass}>
        本服务条款（下称“条款”）规范你对 WriteFit 的使用。创建账户或使用本服务，即表示你同意本条款。
      </p>

      <h2 className={h2Class}>1. 服务说明</h2>
      <p className={pClass}>
        WriteFit 是一个 AI 写作训练工具。它为你提供每日写作练习、保存你的练习历史，并通过你自己配置的第三方
        AI 服务商为你的写作生成反馈。
      </p>

      <h2 className={h2Class}>2. 账户责任</h2>
      <ul className={ulClass}>
        <li>你有责任对账户凭据保密，并对账户下的所有活动负责。</li>
        <li>你必须提供准确的注册信息并保持其更新。</li>
        <li>你必须年满 13 周岁（或达到你所在司法辖区要求的最低年龄）才能使用 WriteFit。</li>
      </ul>

      <h2 className={h2Class}>3. 你的内容</h2>
      <p className={pClass}>
        你对自己在 WriteFit
        中撰写的一切内容（练习、草稿、句子和灵感）保留完整的所有权。我们不对你的内容主张任何知识产权。我们存储和处理你的内容，仅为向你提供服务。
      </p>

      <h2 className={h2Class}>4. AI 反馈</h2>
      <p className={pClass}>
        AI
        生成的反馈仅供参考和练习之用。它可能不准确、不完整或不适合你的具体情况，也不构成任何类型的专业建议（包括法律、医疗、教育或职业建议）。你需自行承担使用反馈的责任。
      </p>

      <h2 className={h2Class}>5. 自带密钥（BYOK）</h2>
      <p className={pClass}>
        WriteFit 允许你使用自己的 API 密钥连接自己的第三方 AI
        服务商账户。在这种情况下：
      </p>
      <ul className={ulClass}>
        <li>
          你与 AI 服务商之间的关系——包括定价、用量限制和数据处理——完全属于你与其之间的事宜。
        </li>
        <li>你有责任遵守该服务商的条款，并承担你的 API 密钥产生的任何费用。</li>
        <li>
          你的 API 密钥存储在你浏览器的 localStorage
          中，而不是我们的服务器上。妥善保管它是你的责任。
        </li>
      </ul>

      <h2 className={h2Class}>6. 可接受使用</h2>
      <p className={pClass}>你同意不会：</p>
      <ul className={ulClass}>
        <li>滥用本服务、干扰其运行或影响其他用户。</li>
        <li>
          对本服务进行逆向工程、反编译或试图提取其源代码（法律允许的情形除外）。
        </li>
        <li>对本服务或其 API 进行抓取、爬取或发送自动化批量请求。</li>
        <li>将本服务用于任何违法、有害或侵犯他人权利的用途。</li>
      </ul>

      <h2 className={h2Class}>7. 服务可用性</h2>
      <p className={pClass}>
        WriteFit 按“现状”和“可用”状态提供。我们不保证服务不中断、及时、安全或无错误，并可能随时修改、暂停或终止服务的任何部分。
      </p>

      <h2 className={h2Class}>8. 终止</h2>
      <p className={pClass}>
        你可以随时停止使用 WriteFit，并在设置页面删除你的账户。对于违反本条款的账户，我们可能会暂停或终止。
      </p>

      <h2 className={h2Class}>9. 责任限制</h2>
      <p className={pClass}>
        在法律允许的最大范围内，WriteFit
        及其运营方不对因你使用本服务而产生的任何间接、附带、特殊、后果性或惩罚性损害，或任何数据、利润或商誉损失承担责任。我们就与本服务相关的任何索赔所承担的全部责任，以你在索赔发生前十二个月内支付给我们的金额为限（如果你免费使用本服务，则为零）。
      </p>

      <h2 className={h2Class}>10. 条款变更</h2>
      <p className={pClass}>
        我们可能会不时更新本条款。更新时，我们会修改上方的“最后更新”日期。变更后继续使用
        WriteFit，即表示你接受更新后的条款。
      </p>

      <h2 className={h2Class}>11. 联系我们</h2>
      <p className={pClass}>
        如果你对本条款有任何疑问，请联系我们：
        <a
          href="mailto:aifeefee70@gmail.com"
          className="text-primary hover:underline"
        >
          aifeefee70@gmail.com
        </a>
        。
      </p>

      <p className="mt-12 border-t border-border pt-6 text-sm">
        <Link href="/" className="text-primary hover:underline">
          &larr; 返回首页
        </Link>
      </p>
    </main>
  );
}
